version: "3"
services:
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - 22181:2181
        restart: always
        networks:
            - shared_network

    kafka:
        image: confluentinc/cp-kafka:latest
        depends_on:
            - zookeeper
        environment:
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        ports:
            - 29092:29092
        restart: always
        networks:
            - shared_network

    kafka-setup:
        image: confluentinc/cp-kafka:latest
        depends_on:
            - kafka
        command:
            - bash
            - -c
            - |
                sleep 40
                kafka-topics --create --topic post --partitions 3 --replication-factor 1 --bootstrap-server kafka:9092
                kafka-topics --create --topic monitoring --partitions 3 --replication-factor 1 --bootstrap-server kafka:9092
                kafka-topics --create --topic post_text --partitions 3 --replication-factor 1 --bootstrap-server kafka:9092
                kafka-topics --create --topic post_photo --partitions 3 --replication-factor 1 --bootstrap-server kafka:9092
                kafka-topics --create --topic post_audio --partitions 3 --replication-factor 1 --bootstrap-server kafka:9092
                kafka-topics --create --topic post_video --partitions 3 --replication-factor 1 --bootstrap-server kafka:9092
                kafka-topics --create --topic post_exchange --partitions 3 --replication-factor 1 --bootstrap-server kafka:9092
        networks:
            - shared_network

networks:
  shared_network:
    external: true