version: "3"
services:
    zookeeper:
        image: bitnami/zookeeper
        ports:
            - "2181:2181"
        environment:
            ALLOW_ANONYMOUS_LOGIN: "yes"

    kafka:
        image: wurstmeister/kafka
        depends_on:
            - zookeeper
        command: ["sh", "-c", "sleep 30 && start-kafka.sh"]
        environment:
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: >-
                post_topic:3:1,
                monitoring_topic:3:1,
                post_text_topic:3:1,
                post_photo_topic:3:1,
                post_audio_topic:3:1,
                post_video_topic:3:1,
                post_result_topic:3:1
        ports:
            - "29092:29092"