version: "3"
services:
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - 22181:2181

    kafka:
        image: confluentinc/cp-kafka:latest
        depends_on:
            - zookeeper
        environment:
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        ports:
            - 29092:29092

    kafka-setup:
        image: confluentinc/cp-kafka:latest
        depends_on:
            - kafka
        command:
            - bash
            - -c
            - |
                sleep 40 # wait for kafka to start
                bin/kafka-topics --create --topic post_topic --partitions 3 --replication-factor 1 --bootstrap-server kafka:9092
                bin/kafka-topics --create --topic monitoring_topic --partitions 3 --replication-factor 1 --bootstrap-server kafka:9092
                bin/kafka-topics --create --topic post_text_topic --partitions 3 --replication-factor 1 --bootstrap-server kafka:9092
                bin/kafka-topics --create --topic post_photo_topic --partitions 3 --replication-factor 1 --bootstrap-server kafka:9092
                bin/kafka-topics --create --topic post_audio_topic --partitions 3 --replication-factor 1 --bootstrap-server kafka:9092
                bin/kafka-topics --create --topic post_video_topic --partitions 3 --replication-factor 1 --bootstrap-server kafka:9092
                bin/kafka-topics --create --topic post_result_topic --partitions 3 --replication-factor 1 --bootstrap-server kafka:9092
